feat(FSADT1-1353): add Frontend Fuzzy matching on Business information for Individuals
bcgov/nr-forest-client pull request #1073
Opened 2024-08-12 14:49 UTC by fterra-encora

# Description

- Calls the fuzzy matching API;
- Displays notification with the errors;
- Highlights the related fields either as error or warning;
- Manages the Review statement checkbox.

Also the following unrelated items:
- Fixes the validation for Acronym on BC registered business;
- Puts back some recently removed test assertions.

Fixes [FSADT1-1353](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1353)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation update

# How Has This Been Tested?

- [ ] New unit tests
- [ ] New integrated tests
- [ ] New component tests
- [ ] New end-to-end tests
- [ ] New user flow tests
- [ ] No new tests are required
- [ ] Manual tests (description below)
- [ ] Updated existing tests

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2024-08-12 16:35 UTC, paulushcgcj requested changes

2024-08-12 16:35 UTC, paulushcgcj commented on frontend/cypress/e2e/FormStaffPage.cy.ts
> +        Helper function to help organize the test steps in a way that resembles the way you would
Why this approach instead of using `describe` and `it`? Is there any issues with it?

2024-08-12 22:27 UTC, paulushcgcj approved these changes

2024-08-13 04:57 UTC, mamartinezmejia approved these changes

2024-08-13 04:58 UTC, merged