feat: Persist client information in postgres
bcgov/nr-forest-client pull request #352
Opened 2023-02-17 15:25 UTC by brunoMarchiEncora

# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

2023-02-21 23:54 UTC, paulushcgcj requested changes
As @brunoMarchiEncora is on leave I will be doing the changes myself.

A few things that require some adjustments are:

- [x] the return of the submission needs to be 201
- [ ] after creating, return the `Location` header
- [ ] after creating, return the `x-sub-id` header
- [ ] the URL should be `/api/clients/submissions`

2023-02-21 23:54 UTC, paulushcgcj commented on backend/src/main/resources/db/migration/V1__initializing_data.sql
> +alter table nrfc.submission alter column submission_id set default nextval('nrfc.submission_id_seq');
@mamartinezmejia can you review this part, please?

2023-02-22 00:03 UTC, mamartinezmejia approved these changes

2023-02-22 00:03 UTC, paulushcgcj approved these changes

2023-02-22 00:04 UTC, merged