feat(FE:FSADT1-814): Vertical wizard (breadcrumb)
bcgov/nr-forest-client pull request #515
Opened 2023-07-05 17:42 UTC by fterra-encora

# Description

Set the wizard (breadcrumb) vertically when the resolution of a screen is small

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Resize the browser window. Any width above or equal to 672 px should display the steps horizontally. Any width below it should display the steps vertically. (Automated tests were written with GWT/Cypress tool to check the steps layout according to different screen widths.)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

2023-07-05 20:21 UTC, paulushcgcj requested changes
Please, also change the other values to `rem` instead of `px`. We are moving away from hard values

2023-07-05 20:21 UTC, paulushcgcj commented on frontend/src/components/wizard/WizardProgressIndicatorComponent.vue
> +  height: 58px;
Convert from pixels to rem

2023-07-06 18:22 UTC, fterra-encora commented on frontend/src/components/wizard/WizardProgressIndicatorComponent.vue
> +  height: 58px;
done

2023-07-10 19:05 UTC, paulushcgcj approved these changes

2023-07-10 19:06 UTC, merged